### ISSUE TITLE
Bundler version not displaying with omnibus-toolchain

### ISSUE THREAD

**Issue by tas50** [chef/omnibus-toolchain#105]
# Describe the problem
In jenkins at the moment the bundler version in omnibus-toolchain is not correctly displaying during the buid.

========================================
= Tool Versions
========================================

Bash.........GNU bash, version 4.3.30(1)-release (x86_64-unknown-linux-gnu)
/opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
	from /opt/angry-omnibus-toolchain/bin/bundle:23:in `<main>'
Bundler......

## Software Version
Latest running in jenkins

## Replication Case
Buiuld chef/chef

**Comment by tas50** [comment]
Long ago. Closing now
