### ISSUE TITLE
Verification for openssl failed due to a missing checksum

### ISSUE THREAD

**Issue by mattray** [chef/omnibus-toolchain#190]
I'm trying to build Chef 16.16.13 and 17.6.18 on Debian 11 with Ruby 2.7.4 and clean builds of omnibus-toolchain consistently fail at the same step. Not sure what changed recently.

```
Progress: |=======================================|
    [NetFetcher: liblzma] I | 2021-10-04T18:12:24+11:00 | Verifying checksum
      [Software: cacerts] I | 2021-10-04T18:12:24+11:00 | Resolving manifest entry for cacerts
    [NetFetcher: cacerts] I | 2021-10-04T18:12:24+11:00 | Downloading from `https://opscode-omnibus-cache.s3.amazonaws.com/cacerts-2021-09-30-f524fc21859b776e18df01a87880efa198112214e13494275dbcbd9bcb71d976'

Progress: |==========================================================================|
    [NetFetcher: cacerts] I | 2021-10-04T18:12:27+11:00 | Verifying checksum
      [Software: openssl] I | 2021-10-04T18:12:27+11:00 | Resolving manifest entry for openssl
#<Thread:0x02137c38 /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/thread_pool.rb:55 run> terminated with exception (report_on_exception is true):
/home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/fetchers/net_fetcher.rb:284:in `digest_type': Verification for openssl failed due to a missing checksum. (Omnibus::ChecksumMissing)

This added security check is used to prevent MITM attacks when downloading the
remote file. You must specify a checksum for each version of software downloaded
from a remote location.
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/fetchers/net_fetcher.rb:133:in `checksum'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/s3_cache.rb:128:in `key_for'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/s3_cache.rb:136:in `url_for'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/fetchers/net_fetcher.rb:149:in `download_url'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/fetchers/net_fetcher.rb:83:in `block in fetch'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/logger.rb:106:in `add'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/logger.rb:59:in `info'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/fetchers/net_fetcher.rb:83:in `fetch'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/software.rb:903:in `fetch'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/project.rb:1067:in `block (3 levels) in download'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/thread_pool.rb:62:in `block (4 levels) in initialize'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/thread_pool.rb:60:in `loop'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/thread_pool.rb:60:in `block (3 levels) in initialize'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/thread_pool.rb:59:in `catch'
	from /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/thread_pool.rb:59:in `block (2 levels) in initialize'
Verification for openssl failed due to a missing checksum.

This added security check is used to prevent MITM attacks when downloading the
remote file. You must specify a checksum for each version of software downloaded
from a remote location.

/home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/fetchers/net_fetcher.rb:284:in `digest_type'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/fetchers/net_fetcher.rb:133:in `checksum'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/s3_cache.rb:128:in `key_for'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/s3_cache.rb:136:in `url_for'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/fetchers/net_fetcher.rb:149:in `download_url'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/fetchers/net_fetcher.rb:83:in `block in fetch'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/logger.rb:106:in `add'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/logger.rb:59:in `info'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/fetchers/net_fetcher.rb:83:in `fetch'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/software.rb:903:in `fetch'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/project.rb:1067:in `block (3 levels) in download'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/thread_pool.rb:62:in `block (4 levels) in initialize'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/thread_pool.rb:60:in `loop'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/thread_pool.rb:60:in `block (3 levels) in initialize'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/thread_pool.rb:59:in `catch'
  /home/omnibus/16.16.13/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-37897ade4832/lib/omnibus/thread_pool.rb:59:in `block (2 levels) in initialize'
```

**Comment by ramereth** [comment]
@mattray I ran into this with InSpec recently. Make sure you're using the correct checkout of omnibus-software when you builds those. They should have the Gemfile.lock in the omnibus dir. Basically it's referencing an openssl version that was recently removed in omnibus-software.

**Comment by mattray** [comment]
@ramereth Thanks, I didn't know that was there, or perhaps I forgot about it when I got into the habit of building my own omnibus-software because of Arm patches I carried. I'll switch to that.
